export default function MethodologyPage() {
  const steps = [
    { title: "Citizen request collection", detail: "Text and voice requests are collected from citizens in Kannada, Telugu, Malayalam or English." },
    { title: "Multilingual AI understanding", detail: "Each request is parsed into a structured record: category, location, severity, urgency and a normalized summary." },
    { title: "Demand aggregation", detail: "Structured requests are grouped by city and category into a demand score and a hotspot status." },
    { title: "Context analysis", detail: "Demand is weighed against infrastructure condition, service capacity and population pressure to produce a context gap score." },
    { title: "Development priority calculation", detail: "Citizen demand and context gap are combined into a single development priority score and band." },
    { title: "AI explanation", detail: "A language model explains the already-calculated score in plain language — it does not change or recompute it." },
  ];

  return (
    <div className="mx-auto max-w-3xl px-6 py-14">
      <h1 className="font-display text-3xl text-text">Methodology</h1>
      <p className="mt-3 text-muted leading-relaxed">
        JanDrishti AI turns citizen requests into a repeatable, six-step pipeline.
        Each step below is deterministic except the final explanation layer.
      </p>

      <ol className="mt-10 space-y-8">
        {steps.map((s, i) => (
          <li key={s.title} className="flex gap-4">
            <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-primary-light text-sm text-primary-light">
              {i + 1}
            </span>
            <div>
              <p className="font-medium text-text">{s.title}</p>
              <p className="mt-1 text-sm text-muted leading-relaxed">{s.detail}</p>
            </div>
          </li>
        ))}
      </ol>

      <div className="mt-12 border border-border bg-surface p-6">
        <p className="text-sm text-muted mb-3">Development priority formula</p>
        <p className="font-display text-xl text-text leading-relaxed">
          Development Priority = 60% Citizen Demand + 40% Context Gap
        </p>
        <p className="mt-4 text-sm text-muted leading-relaxed">
          Context Gap = 40% (100 − Infrastructure Condition) + 35% (100 − Service
          Capacity) + 25% Population Pressure
        </p>
      </div>

      <div className="mt-8 border-l-2 border-accent pl-4">
        <p className="text-sm text-text leading-relaxed">
          Scores shown in this prototype are calculated from synthetic/demo data
          and should not be interpreted as real government infrastructure
          measurements or funding decisions.
        </p>
      </div>

      <div className="mt-8">
        <p className="text-sm font-medium text-text mb-2">A note on AI-generated interpretation</p>
        <p className="text-sm text-muted leading-relaxed">
          Categories, severity, and the development priority score are produced by
          deterministic rules and numerical formulas. Only the written explanation
          in Module 5 is generated by a language model — it interprets a result
          that has already been calculated, and cannot alter it.
        </p>
      </div>
    </div>
  );
}
